### ISSUE TITLE
typo in file nomad_job_files/faas.hcl

### ISSUE THREAD

**Issue by herveleclerc** [hashicorp/faas-nomad#39]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. nomad run -verbose ./nomad_job_files/faas.hcl

What happens?
-------------
faas-nomadd fails with error :

Template: error parsing env template "secrets/gateway.env": error on line 6: missing =
 
-------------------

To fix it edit the file faas.hcl
change 
functions_provider_url="http://{{ env "NOMAD_IP_http" }}:8081/"
{{ range service "prometheus" }}
faas_prometheus_host="{{ .Address }}"
faas_prometheus_port="{{ .Port }}"{{ end }}
{{ range service "nats" }}
**faas_nats_address: "{{ .Address }}"{{ end }}
faas_nats_port: 4222**
EOH

to

functions_provider_url="http://{{ env "NOMAD_IP_http" }}:8081/"
{{ range service "prometheus" }}
faas_prometheus_host="{{ .Address }}"
faas_prometheus_port="{{ .Port }}"{{ end }}
{{ range service "nats" }}
faas_nats_address="{{ .Address }}"{{ end }}
faas_nats_port=4222
EOH

**Comment by alexellis** [comment]
What's the difference between the two?

How far did you get after this change?

**Comment by acornies** [comment]
This typo affects Nomad's specific template rendering stanza for environment var injection into a container. I've confirmed (Aug 23, 2018) the suggested change properly deploys faas components in a Nomad environment.

**Comment by alexellis** [comment]
@nicholasjackson

**Comment by nicholasjackson** [comment]
Thanks, all merged
