### ISSUE TITLE
Basic auth not implemented (Vault in future)

### ISSUE THREAD

**Issue by acornies** [hashicorp/faas-nomad#47]
What are the steps to reproduce this issue?
-------------------------------------------
1. install faas-cli, trigger `faas-cli login -address ...`
2. trigger a system endpoint

What happens?
-------------
faas-nomad is open internally, no auth strategy

What were you expecting to happen?
----------------------------------
faas-nomad respects basic auth passed in from gateway, and by default basic auth should be on?

Any logs, error output, etc?
----------------------------
N/A

Any other comments?
-------------------
Creating this issue for tracking. I believe there is support for this in the faas-provider now, so it's just a matter of implementing that to get parity with other providers and improving from there.

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu 16.04 x64

**OpenFaaS Version:** 0.9.2

**Nomad Version:** 0.2.27

**Comment by nicholasjackson** [comment]
Thanks Andrew, I have merged this in #46
