### ISSUE TITLE
Function secrets need default Vault policy

### ISSUE THREAD

**Issue by acornies** [hashicorp/faas-nomad#54]
What are the steps to reproduce this issue?
-------------------------------------------
1. Use the UI or faas-cli to deploy a function w/ one or more secrets using the Nomad provider

What happens?
-------------
Function is never "ready" due to missing Vault policy in certain Nomad configurations

What were you expecting to happen?
----------------------------------
Functions can be deployed with secrets using Vault Nomad integration

Any logs, error output, etc?
----------------------------
N/A

Any other comments?
-------------------
When a Nomad client is configured with a Vault master token this isn't a problem, but when Nomad Vault integration is configured to request token on-the-fly for functions (from the Nomad servers) a policy is needed to this behaviour to work.

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu 16.04 x64

**OpenFaaS Version:** 0.9.3

**Nomad Version:** 0.8.4

**Comment by nicholasjackson** [comment]
Sorry @acornies just merged your PR, will do a tagged build in 10 mins

**Comment by acornies** [comment]
Resolved in #53
