### ISSUE TITLE
Implement /system/secrets and use Nomad's configured Vault API

### ISSUE THREAD

**Issue by acornies** [hashicorp/faas-nomad#69]
What are the steps to reproduce this issue?
-------------------------------------------
1. download latest faas-cli ()
2. download latest gateway >= 0.9.14
3. try out faas-cli ~= 0.8.3 using `faas-cli secret ...`

What happens?
-------------
The secret endpoints are not yet supported.

Any other comments?
-------------------
Adding this for tracking. The approach so far is to implement against Vault's API using the already-established convention of the default Vault policy and key prefix from faas-nomad.

**Comment by alexellis** [comment]
I didn't realize this wasn't implemented yet. I mentioned Nomad being available in the blog post, but given that this provider has fewer users this may be something that goes unnoticed in the interim.

https://www.openfaas.com/blog/unified-secrets/

**Comment by acornies** [comment]
Working on it...

**Comment by acornies** [comment]
@nicholasjackson My implementation thus far uses the Nomad agent self config, which contains the Vault info. Ultimately faas-nomad needs a management style Nomad ACL token, which will provide the Vault token that's configured on the Nomad agent. It's very much tied to the permissions Nomad ultimately has.

**Comment by acornies** [comment]
I'd appreciate some feedback here: https://github.com/acornies/faas-nomad/commit/57bd520b104c896ce19a31c334c64ecfba4f4061 when you get a change. I'll keep going down this road unless I hear otherwise.

**Comment by acornies** [comment]
Addressed in #70 using Vault approle and secrets v1.
