### ISSUE TITLE
Issue in Vagrant up

### ISSUE THREAD

**Issue by shishir-a412ed** [hashicorp/faas-nomad#94]
What are the steps to reproduce this issue?
-------------------------------------------
1. Vagrant up

What happens?
-------------

```
    default: Error querying node status: Get https://192.168.50.2:4646/v1/nodes: dial tcp 192.168.50.2:4646: connect: connection refused
    default: Error querying node status: Get https://192.168.50.2:4646/v1/nodes: dial tcp 192.168.50.2:4646: connect: connection refused
    default: Error querying node status: Get https://192.168.50.2:4646/v1/nodes: dial tcp 192.168.50.2:4646: connect: connection refused
    default: Error querying node status: Get https://192.168.50.2:4646/v1/nodes: dial tcp 192.168.50.2:4646: connect: connection refused
    default: Error querying node status: Get https://192.168.50.2:4646/v1/nodes: dial tcp 192.168.50.2:4646: connect: connection refused
    default: Error querying node status: Get https://192.168.50.2:4646/v1/nodes: dial tcp 192.168.50.2:4646: connect: connection refused
    default: Error querying node status: Get https://192.168.50.2:4646/v1/nodes: dial tcp 192.168.50.2:4646: connect: connection refused
    default: Error querying node status: Get https://192.168.50.2:4646/v1/nodes: dial tcp 192.168.50.2:4646: connect: connection refused
```

What were you expecting to happen?
----------------------------------
Complete the vagrant setup successfully.

What versions of the software are you using?
----------------------------------------
**Operating System:** …
macOS Catalina v10.15.5

**OpenFaaS Version:** …

**Nomad Version:** …

**Comment by shishir-a412ed** [comment]
@acornies Any pointers on how to debug?

**Comment by masimpkin** [comment]
There seems like it may be an issue with "nomad-formula/nomad/defaults.yaml". It specifies a default directory of "/etc/nomad" instead of "/etc/nomad.d". If you modify "/etc/systemd/system/nomad.service" and execute "systemctl daemon-reload", you can then start nomad with "service nomad start". There are still other issues though.
